pipeline:
  name: DeploytoDev
  identifier: DeploytoDev
  projectIdentifier: lab_ravim_cd
  orgIdentifier: training_13thNov
  tags: {}
  stages:
    - stage:
        name: DeployApp
        identifier: DeployApp
        description: "Hello from Git"
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: RaviService
          environment:
            environmentRef: org.dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dev_infra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
